name: TEST This Application Needs a New Layers
description: test
title: This Application Needs a New Layers
labels: ["enhancement", "new data"]
assignees:
  - CyndiAndersen, marshallrobinson
body:
  - type: textarea
    id: requestReason
    attributes:
        label: Why do you feel this application needs what you're requesting?
        placeholder: I need this new layer added because [...] (for each layer)
    validations:
        required: true
  - type: textarea
    id: valueReason
    attributes:
        label: Describe the layer(s) you'd like to add
        placeholder: A clear and concise description of the new layers you'd like to add.
    validations:
        required: true
  - type: textarea
    id: moreContext
    attributes:
        label: Additional Context
        placeholder: Add any other context or screenshots about the feature request here.
    validations:
        required: false
   - type: textarea
    id: popupDetails
    description: Following the current popup-formatting of other layers in this applications, what attributes would you like displaced for the new layer(s)? 
    attributes:
        label: Popup Formatting
        placeholder: Following the current popup-formatting of other layers in this applications, what attributes would you like displaced for the new layer(s)?
    validations:
        required: true
  - type: textarea
    id: panelEdits
    description: Add any other context or screenshots about the feature request here.
    attributes:
        label: Text for "About," "Database Contents," etc. Panels
        placeholder: Popup Title, Attribute Name, Attribute Value (w/desired units if necessary), etc.
    validations:
        required: true      
  - type: input
    id: dataLocation
    attributes:
        label: Folder path of data
        placeholder: G:\Shared drives\UGS_Shared\...
    validations:
        required: true
