name: Test (Don't Use Yet)
description: This is just a test
title: "Title: **Feature or new layer you wish this application had)**"
labels: ["enhancement", "new data"]
assignees:
  - CyndiAndersen, marshallrobinson
body:
  - type: textarea
    id: requestReason
    attributes:
        label: Why do you feel this application needs what you're requesting?
        description: Does this need a sub-header?
        placeholder: I need this new layer added because [...], or
A clear and concise description of what you feel the problem is. Ex. I'm always frustrated when [...]
    validations:
        required: true
  - type: textarea
    id: valueReason
    attributes:
        label: Describe the solution you'd like and why it builds value:
        description: Does this need a sub-header?
        placeholder: A clear and concise description of what you want to happen and what value it will bring.
    validations:
        required: true
  - type: textarea
    id: moreContext
    attributes:
        label: Additional Context:
        description: Does this need a sub-header?
        placeholder: Add any other context or screenshots about the feature request here.
    validations:
        required: true
  - type: input
    id: dataLocation
    attributes:
        label: Folder path of data:
        description: Does this need a sub-header?
        placeholder: G:\Shared drives\UGS_Shared\...
    validations:
        required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
  - type: markdown
    attributes:
        value: "## Review Process | **Data Layer Submissions**
**(If adding new data layers to the application, your data will be reviewed and checked off by the following people using Github):

**Database Design Review:**
-GIS Analyst or Data Owner
-GIS Manager
-Database Manager

**Science & Database Content Review:**
-Data Owner
-Program Manager
-Technical Reviewer (only the text within the database/app: if it's in full sentence format)

***

**All Other Feature Requests Will Be Prioritized and Considered for Future Application Releases**

   |
        Thanks for taking the time to fill out this form!"